# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "4f20edcb-7ab9-4b8a-a583-98e5f43a37a0"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do 
    
    increment_version_code(
        gradle_file_path: "app/build.gradle",
        app_folder_name: "app"
    )
  
  # build the debug variant
  build_android_app(task: "assembleDebug")
  
  # upload to HockeyApp
  hockey(
     api_token: "API"
  )
end
